#!/bin/bash
echo ---------------systemd files------------;
echo;
ls /etc/systemd/system/|grep agent;
echo;
echo ---------------systemctrl files----------;
echo;
echo; systemctl| grep agent;
echo;
echo ---------------proseses ----------------;
echo; 
ps aux|grep agent
echo;
